# Generated by Django 5.2.6 on 2025-09-12 17:04

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tipo', models.CharField(choices=[('admin', 'Admin'), ('professor', 'Professor'), ('aluno', 'Aluno')], default='admin', max_length=10)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('rg', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True)),
                ('cor_pele', models.CharField(blank=True, choices=[('branca', 'Branca'), ('preta', 'Preta'), ('parda', 'Parda'), ('amarela', 'Amarela'), ('indigena', 'Indígena')], max_length=20, null=True)),
                ('senha_temporaria', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'usuarios_usuarios',
                'permissions': [('detail_usuario', 'Pode ver o detalhe de usuário')],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ch', models.IntegerField(default=20)),
                ('turmas', models.ManyToManyField(to='core.turma')),
                ('professores', models.ManyToManyField(limit_choices_to={'tipo': 'professor'}, to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_1_semestre1', models.FloatField(blank=True, null=True)),
                ('nota_2_semestre1', models.FloatField(blank=True, null=True)),
                ('paralela_1', models.FloatField(blank=True, null=True)),
                ('nota_1_semestre2', models.FloatField(blank=True, null=True)),
                ('nota_2_semestre2', models.FloatField(blank=True, null=True)),
                ('paralela_2', models.FloatField(blank=True, null=True)),
                ('nota_recuperacao', models.FloatField(blank=True, null=True)),
                ('status_final', models.CharField(blank=True, max_length=30)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.materia')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.turma')),
                ('aluno', models.ForeignKey(limit_choices_to={'tipo': 'aluno'}, on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorMateriaTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.materia')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.turma')),
                ('professor', models.ForeignKey(limit_choices_to={'tipo': 'professor'}, on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'unique_together': {('professor', 'materia', 'turma')},
            },
        ),
        migrations.CreateModel(
            name='AlunoTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_matricula', models.DateField(auto_now_add=True)),
                ('ano_letivo', models.CharField(blank=True, max_length=10, null=True)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.turma')),
                ('aluno', models.ForeignKey(limit_choices_to={'tipo': 'aluno'}, on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'unique_together': {('aluno', 'turma')},
            },
        ),
    ]
