# Generated by Django 5.2.1 on 2025-07-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_professormateriaturma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='nota_1_semestre',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='nota_2_semestre',
        ),
        migrations.AddField(
            model_name='nota',
            name='nota_1_semestre1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='nota_1_semestre2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='nota_2_semestre1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='nota_2_semestre2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cor_pele',
            field=models.CharField(blank=True, choices=[('branca', 'Branca'), ('preta', 'Preta'), ('parda', 'Parda'), ('amarela', 'Amarela'), ('indigena', 'Indígena')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='status_final',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
