# Generated by Django 5.2.1 on 2025-06-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_professormateriaturma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nota',
            old_name='nota_1_semestre',
            new_name='nota_1_semestre1',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='nota_2_semestre',
            new_name='nota_1_semestre2',
        ),
        migrations.AddField(
            model_name='nota',
            name='nota_2_semestre1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='nota',
            name='nota_2_semestre2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cor_pele',
            field=models.CharField(blank=True, choices=[('branca', 'Branca'), ('preta', 'Preta'), ('parda', 'Parda'), ('amarela', 'Amarela'), ('indigena', 'Indígena')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True),
        ),
    ]
