# Generated by Django 5.2.1 on 2025-07-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_nota_1_semestre_nota_nota_1_semestre1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='nota_1_semestre1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='nota_1_semestre2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='nota_2_semestre1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='nota_2_semestre2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='status_final',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
