# Generated by Django 5.2.2 on 2025-09-07 01:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_nota_nota_1_semestre1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunoturma',
            name='ano_letivo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='alunoturma',
            name='data_matricula',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materia',
            name='ch',
            field=models.IntegerField(default=20),
        ),
    ]
